// constants/maps.js — MAP_DEFS: progressão, dificuldade e visual por mapa
// Para adicionar um mapa: copie um bloco existente e ajuste os valores.

const { MAP_SIZE } = require('./engine');

const MAP_DEFS = {};

// ── Mapa 1: Mar dos Corsários ─────────────────────────────────────────────────
MAP_DEFS[1] = {
  name:        'Mar dos Corsários',
  xpRequired:  0,
  xpToAdvance: 1800,
  size:         MAP_SIZE,
  sideMap: [{norte: 2}],
  npc: {
    count:        6,
    baseHp:       100,
    baseDamage:   8,
    fireInterval: 3000,
    names:        'Abyssal Stalker',
    hullColor:    0x3a1a0a,
    sailColor:    0xcc3333,
    flagColor:    0xcc2222,
    xpPerKill:    12,
    goldMin:      30,
    goldMax:      40,
    dobraoChance: 0,
    dobraoMin:    0,
    dobraoMax:    0,
    goldMult:     1.0,
    hpPerTier:    0.05,
    dmgPerTier:   0.08,
    goldPerTier:  0.03,
    model:        '/models/monster/abyssal_reef_stalker.glb',
    scale: 20,
    yOffset: -5.4,
    rotOffset: 0,
    hitRadius: 8,
    relicDropChance: 0.01, // 1%
    attacks: ['tentacle_slam', 'tail_slam', 'ink_blast', 'tentacle_sweep', 'claw_slam'],
    ammoTiers: [
      { minKills: 0,   ammo: 'bala_ferro' },
      { minKills: 100, ammo: 'bala_gelo'  },
    ],
  },
  boss: {
    name:        'Giant Crab Octopus',
    baseHp:      1000,
    baseDamage:  20,
    hpPerTier:     0.20,
    dmgPerTier:    0.15,
    rewardPerTier: 0.1,
    regenPerSec:   50,
    regenDelay:    20000,
    killsToSpawn: 20,
    dobraoMin:   15,
    dobraoMax:   25,
    hullColor:   0x1a0505,
    sailColor:   0x220000,
    model:       '/models/monster/giant_crab_octopus.glb',
    scale: 19,
    yOffset: -20,
    rotOffset: 0,
    hitRadius: 12,
    attacks: ['impale_line', 'charge_line', 'lava_breath', 'cleave', 'arcane_nova'],
    rarities: [
      { id: 'normal',   label: 'Normal',   hpMult: 1.0, rewardMult: 1.0,  chance: 0.40, color: '#888', bg: 'rgba(40,40,40,0.92)' },
      { id: 'raro',     label: 'Raro',     hpMult: 1.5, rewardMult: 1.5,  chance: 0.30, color: '#44f', bg: 'rgba(10,20,60,0.92)' },
      { id: 'especial', label: 'Especial', hpMult: 2.0, rewardMult: 2.0,  chance: 0.20, color: '#a4f', bg: 'rgba(40,10,60,0.92)' },
      { id: 'infernal', label: 'Infernal', hpMult: 3.0, rewardMult: 3.0,  chance: 0.10, color: '#f80', bg: 'rgba(60,15,0,0.92)' },
    ],
  },
  visual: {
    bgColor:          0x2f476a,
    fogColor:         0x6d82a2,
    fogDensity:       0,
    ambientColor:     0xfbff00,
    ambientIntensity: 0.15,
    sunColor:         0xffd080,
    sunIntensity:     2.6,
    ocean1:           0xffffff,
    ocean2:           0xffffff,
    hasMoon:          true,
    hasDenseNebula:   false,
  },
};

// ── Mapa 2: Baía das Sombras ──────────────────────────────────────────────────
MAP_DEFS[2] = {
  name:        'Baía das Sombras',
  xpRequired:  1800,
  xpToAdvance: 8000,
  size:         MAP_SIZE,
  sideMap: [{sul: 1, norte: 3}],
  npc: {
    count:        9,
    baseHp:       300,
    baseDamage:   18,
    fireInterval: 3000,
    names:        'Dreadfin Leviathan',
    hullColor:    0x0a0a1a,
    sailColor:    0x553399,
    flagColor:    0x442288,
    xpPerKill:    18,
    goldMin:      80,
    goldMax:      120,
    dobraoChance: 1,
    dobraoMin:    1,
    dobraoMax:    2,
    goldMult:     2.5,
    hpPerTier:    0.09,
    goldPerTier:  0.03,
    model:       '/models/monster/dreadfin_leviathan.glb',
    scale: 19,
    yOffset: 2,
    rotOffset: 0,
    hitRadius: 8,
    relicDropChance: 0.03, // 3%
    attacks: ['bite', 'tail_slam', 'shockwave', 'venom_pool', 'deep_surge'],
    ammoTiers: [
      { minKills: 200, ammo: 'bala_gelo' },
      { minKills: 400, ammo: 'bala_bala_fogo' },
    ],
  },
  boss: {
    name:        'Abyssal Sovereign',
    baseHp:      1200,
    baseDamage:  35,
    hpPerTier:     0.25,
    dmgPerTier:    0.18,
    rewardPerTier: 0.1,
    regenPerSec:   80,
    regenDelay:    20000,
    killsToSpawn: 30,
    dobraoMin:   30,
    dobraoMax:   40,
    hullColor:   0x050510,
    sailColor:   0x330033,
    model:       '/models/monster/abyssal_sovereign.glb',
    scale: 13,
    yOffset: 3.5,
    rotOffset: 0,
    hitRadius: 12,
    attacks: ['tail_slam', 'shockwave', 'lava_breath', 'meteor_drop', 'impale_line'],
    rarities: [
      { id: 'normal',   label: 'Normal',   hpMult: 1.0, rewardMult: 1.0,  chance: 0.40, color: '#888', bg: 'rgba(40,40,40,0.92)' },
      { id: 'raro',     label: 'Raro',     hpMult: 1.5, rewardMult: 1.5,  chance: 0.30, color: '#44f', bg: 'rgba(10,20,60,0.92)' },
      { id: 'especial', label: 'Especial', hpMult: 2.0, rewardMult: 2.0,  chance: 0.20, color: '#a4f', bg: 'rgba(40,10,60,0.92)' },
      { id: 'infernal', label: 'Infernal', hpMult: 3.0, rewardMult: 3.0,  chance: 0.10, color: '#f80', bg: 'rgba(60,15,0,0.92)' },
    ],
  },
  visual: {
    bgColor:          0x223768,
    fogColor:         0x1b2722,
    fogDensity:       0.0025,
    ambientColor:     0x1e2207,
    ambientIntensity: 1,
    sunColor:         0xffe0b0,
    sunIntensity:     1.8,
    ocean1:           0x206f5e,
    ocean2:           0x063830,
    hasMoon:          false,
    hasDenseNebula:   true,
  },
};

// ── Mapa 3: Ilha do Comércio ──────────────────────────────────────────────────
MAP_DEFS[3] = {
  name:        'Ilha do Comércio',
  xpRequired:  13000,
  xpToAdvance: 20000,
  size:         MAP_SIZE * 3,
  sideMap: [{sul: 2, left: 4}],
  npc: {
    count:        15,
    baseHp:       400,
    baseDamage:   200,
    fireInterval: 3200,
    names:        'Gilded Reef Manta',
    hullColor:    0x2a5a3a,
    sailColor:    0x88cc66,
    flagColor:    0x66aa44,
    xpPerKill:    30,
    goldMin:      120,
    goldMax:      180,
    dobraoChance: 1,
    dobraoMin:    2,
    dobraoMax:    5,
    goldMult:     3.0,
    hpPerTier:    0.12,
    goldPerTier:  0.05,
    model:       '/models/monster/gilded_reef_manta.glb',
    scale: 13,
    yOffset: 0,
    rotOffset: 0,
    hitRadius: 8,
    relicDropChance: 0.05, // 5%
    attacks: ['bite', 'charge_line', 'venom_pool', 'forked_shot', 'shockwave', 'impale_line'],
  },
  boss: {
    name:        'Harbor Warden The Coinbreaker',
    baseHp:      2000,
    baseDamage:  300,
    hpPerTier:     0.30,
    dmgPerTier:    0.20,
    rewardPerTier: 0.1,
    regenPerSec:   120,
    regenDelay:    20000,
    killsToSpawn:  40,
    dobraoMin:     50,
    dobraoMax:     80,
    hullColor:     0x553311,
    sailColor:     0x996633,
    model:       '/models/monster/harbor_warden_the_coinbreaker.glb',
    scale: 8.5,
    yOffset: 3.5,
    rotOffset: 0,
    hitRadius: 12,
    attacks: ['bite', 'charge_line', 'venom_pool', 'forked_shot', 'shockwave', 'impale_line'],
    rarities: [
      { id: 'normal',   label: 'Normal',   hpMult: 1.0, rewardMult: 0.1,  chance: 0.40, color: '#888', bg: 'rgba(40,40,40,0.92)' },
      { id: 'raro',     label: 'Raro',     hpMult: 1.5, rewardMult: 1.5,  chance: 0.30, color: '#44f', bg: 'rgba(10,20,60,0.92)' },
      { id: 'especial', label: 'Especial', hpMult: 2.0, rewardMult: 2.0,  chance: 0.20, color: '#a4f', bg: 'rgba(40,10,60,0.92)' },
      { id: 'infernal', label: 'Infernal', hpMult: 3.0, rewardMult: 3.0,  chance: 0.10, color: '#f80', bg: 'rgba(60,15,0,0.92)' },
    ],
  },
  visual: {
    bgColor:          0x083020,
    fogColor:         0x000000,
    fogDensity:       0.0029,
    ambientColor:     0x97752b,
    ambientIntensity: 1,
    sunColor:         0xffe0b0,
    sunIntensity:     1.8,
    ocean1:           0x083020,
    ocean2:           0x083020,
    hasMoon:          false,
    hasDenseNebula:   true,
  },
  market: {
    center: { x: 0, z: 0 },
    islandRadius: 190,
    detectionRadius: 250,
    securyRadius: 300,
    model: '/models/places/merchant_tropical.glb',
    scale: 8.5,
    yOffset: -9,
    rotOffset: 0,
    items: [
      {
        shipUpgrades: [
          {
            id: 'ship_hp_upgrade',
            name: 'Vida do Navio',
            description: '+1000 HP',
            icon: '❤️',
            hpBonus: 1000,
            price: 5000,
            currency: 'dobrao',
            maxLevel: 5
          },
          {
            id: 'ship_defense_upgrade',
            name: 'Defesa do Navio',
            description: '+5% Defesa',
            icon: '🛡️',
            defenseBonus: 0.05,
            price: 10000,
            currency: 'dobrao',
            maxLevel: 5
          },
        ],
        cannonUpgrades: [
          {
            id: 'cannon_attack_speed_upgrade',
            name: 'Velocidade de Ataque',
            description: '-1s Cooldown',
            icon: '⚡',
            field: 'as',
            attackSpeedBonus: -1000,
            price: 100000, currency: 'gold',
            ironPlatesPrice: 10,
          },
          {
            id: 'cannon_range_upgrade',
            name: 'Alcance',
            description: '+50 Range',
            icon: '🎯',
            field: 'rn',
            rangeBonus: 50,
            price: 5000, currency: 'dobrao',
            ironPlatesPrice: 20,
          },
          {
            id: 'cannon_damage_upgrade',
            name: 'Dano',
            description: '+10% Dano',
            icon: '💥',
            field: 'dm',
            damageBonus: 0.10,
            price: 10000, currency: 'dobrao',
            ironPlatesPrice: 30,
          },
        ],
      }
    ]
  }
};

// ── Mapa 4: Ilha do Farol ─────────────────────────────────────────────────────
MAP_DEFS[4] = {
  name:         'Ilha do Farol',
  sideMap: [{norte: 6, right: 3}],
  xpRequired:   20000,
  xpToAdvance:  30000,
  size:          MAP_SIZE * 2,
  npc: {
    count:        3,
    baseHp:       8000,
    baseDamage:   1000,
    fireInterval: 3200,
    names:        'Storm Wyvern',
    hullColor:    0x2a5a3a,
    sailColor:    0x88cc66,
    flagColor:    0x66aa44,
    xpPerKill:    106,
    goldMin:      1800,
    goldMax:      2100,
    dobraoChance: 1,
    dobraoMin:    300,
    dobraoMax:    400,
    goldMult:     3.0,
    hpPerTier:    0.12,
    goldPerTier:  0.05,
    model:       '/models/monster/storm_wyvern.glb',
    scale: 7,
    yOffset: 50,
    rotOffset: 0,
    hitRadius: 8,
    relicDropChance: 0.11, // 11% — poucos NPCs, mapa difícil
    attacks: ['impale_line', 'heavy_stomp', 'venom_pool', 'whirlwind', 'lava_breath', 'piercing_beam', 'charge_line', 'cross_blast'],
  },
  boss: null,
  visual: {
    bgColor:          0x0d1b2a,
    fogColor:         0x3a5a7a,
    fogDensity:       0.0008,
    ambientColor:     0xffd080,
    ambientIntensity: 0.55,
    sunColor:         0xffb060,
    sunIntensity:     1.8,
    ocean1:           0x1a3a5a,
    ocean2:           0x0d2540,
    hasMoon:          true,
    hasDenseNebula:   false,
  },
  lighthouse: {
    center:          { x: 0, z: 0 },
    islandRadius:    80,
    detectionRadius: 160,
    model:           '/models/places/lighthouse_islan.glb',
    scale:           5,
    yOffset:         0,
    rotOffset:       0,
  },
  dailyMissionCount: 20,
  dailyMissions: [
    { id:'kill_elite',            icon:'🔥',  label:'Derrotar 3 inimigos elite',            stat:'eliteKills',      target:3,      reward:{ dobrao:15000 } },
    { id:'kill_with_cannons',     icon:'💣',  label:'Derrotar 100 inimigos com canhão',     stat:'cannonKills',     target:100,    reward:{ gold:50000 } },
    { id:'kill_without_damage',   icon:'🛡️',  label:'Derrotar 20 inimigos sem sofrer dano', stat:'perfectKills',    target:20,     reward:{ dobrao:8000 } },
    { id:'assist_boss',           icon:'⚔️',  label:'Participar da derrota de 3 bosses',    stat:'bossAssists',     target:3,      reward:{ dobrao:8000 } },
    { id:'damage_world_boss',     icon:'🩸',  label:'Causar 200000 dano em boss mundial',   stat:'worldBossDamage', target:200000, reward:{ dobrao:12000 } },
    { id:'discover_islands',      icon:'🗺️',  label:'Visitar 5 ilhas diferentes',           stat:'islandsVisited',  target:5,      reward:{ gold:200000 } },
    { id:'travel_distance',       icon:'🧭',  label:'Navegar 20000 metros',                 stat:'distanceSailed',  target:20000,  reward:{ gold:150000 } },
    { id:'visit_lighthouse',      icon:'🕯️',  label:'Visitar o farol',                      stat:'lighthouseVisit', target:1,      reward:{ dobrao:3000 } },
    { id:'sink_ships',            icon:'🚢',  label:'Afundar 5 navios inimigos',            stat:'shipsSunk',       target:5,      reward:{ dobrao:9000 } },
    { id:'fragment_map',          icon:'📦',  label:'Abrir 100 fragmentos de mapa',         stat:'fragmentUse',     target:100,    reward:{ gold:250000 } },
    { id:'buy_items',             icon:'🛒',  label:'Comprar 3 itens no mercado',           stat:'itemsBought',     target:3,      reward:{ gold:120000 } },
    { id:'tank_damage',           icon:'🛡️',  label:'Absorver 200000 dano',                 stat:'damageBlocked',   target:200000, reward:{ gold:200000 } },
    { id:'reef_hunter_stalker',   icon:'🦀',  label:'Derrotar 100 Abyssal Stalker',         stat:'reefKills',       target:100,    reward:{ gold:120000 } },
    { id:'reef_hunter_leviathan', icon:'🦀',  label:'Derrotar 80 Dreadfin Leviathan',       stat:'reefKills',       target:80,     reward:{ gold:120000 } },
    { id:'reef_hunter_manta',     icon:'🦀',  label:'Derrotar 50 Gilded Reef Manta',        stat:'reefKills',       target:50,     reward:{ gold:120000 } },
    { id:'market_guard',          icon:'🏝️',  label:'Defender a ilha mercado',              stat:'marketDefense',   target:30,     reward:{ dobrao:10000 } },
    { id:'lighthouse_keeper',     icon:'🕯️',  label:'Completar missão do farol',            stat:'lighthouseQuest', target:1,      reward:{ dobrao:7000 } },
  ],
};

// ── Mapa 5: Campo de Treino AFK ───────────────────────────────────────────────
MAP_DEFS[5] = {
  name:        'Campo de Treino',
  sideMap:     null,
  xpRequired:  0,
  xpToAdvance: null,
  size:        400,
  npc:         null,
  boss:        null,
  visual: {
    bgColor:          0x050d1a,
    fogColor:         0x0d1a2e,
    fogDensity:       0.006,
    ambientColor:     0x1a2d45,
    ambientIntensity: 0.85,
    sunColor:         0x5577aa,
    sunIntensity:     0.9,
    ocean1:           0x0a1e35,
    ocean2:           0x06101f,
    hasMoon:          false,
    hasDenseNebula:   false,
  },
  training: {
    goldPerHour:    100000,
    maxHours:       8,
    baseDamage:     5000,
    fireInterval:   3000,
    dummy: { x: 0, z: -120 },
    collisionRadius: 18,
    detectionRadius: 150,
    model: '/models/places/massive_defensive_sea_tower.glb',
    scale: 1.5,
    yOffset: 0,
    rotOffset: 0,
  }
};

// ── Mapa 6: Mar das Lamentações ───────────────────────────────────────────────
MAP_DEFS[6] = {
  name:        'Mar das Lamentações',
  sideMap:     [{sul: 4}],
  xpRequired:  30000,
  xpToAdvance: null,
  size:        MAP_SIZE * 2,
  npc:         null,
  boss: {
    name:        'The Drowned Widow',
    baseHp:       40000,
    baseDamage:   1500,
    hpPerTier:     0.30,
    dmgPerTier:    0.15,
    rewardPerTier: 0.1,
    regenPerSec:   120,
    regenDelay:    20000,
    killsToSpawn:  0,
    respawnDelay:  3600000, // 1 hora em ms após ser morta
    dobraoMin:     2000,
    dobraoMax:     5000,
    hullColor:     0x553311,
    sailColor:     0x996633,
    model:       '/models/monster/ghostly_female_spirit.glb',
    scale: 60,
    yOffset: 3.5,
    rotOffset: 0,
    hitRadius: 30,
    relicDropChance: 0.25, // 25% — poucos NPCs, mapa difícil
    attacks: ['ghost_soul_pillars', 'cross_blast', 'sniper_shot', 'wide_flame_cone', 'arcane_nova'],
    auras:   ['ghost_dread_aura'],
    rarities: [
      { id: 'infernal', label: 'Infernal', hpMult: 1.0, rewardMult: 1, chance: 1, color: '#f80', bg: 'rgba(60,15,0,0.92)' },
    ],
  },
  visual: {
    bgColor:          0x0d1b2a,
    fogColor:         0x3a5a7a,
    fogDensity:       0.0008,
    ambientColor:     0xffd080,
    ambientIntensity: 0.55,
    sunColor:         0xffb060,
    sunIntensity:     1.8,
    ocean1:           0x1a3a5a,
    ocean2:           0x0d2540,
    hasMoon:          true,
    hasDenseNebula:   false,
  },
};

module.exports = { MAP_DEFS };
