// constants/ships.js — Navios, slots de relíquia e upgrades de ilha

// ── SHIP_DEFS ─────────────────────────────────────────────────────────────────
const SHIP_DEFS = {
  fragata: {
    price: 0, 
    currency: 'free',
    hp: 200, 
    maxCannons: 5, 
    sails: 1,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/fragata.glb',
    scale: 2.5, yOffset: -12.3, rotOffset: 270 * Math.PI / 180,
  },
  sloop: {
    price: 5000, 
    currency: 'gold',
    hp: 500, 
    maxCannons: 10, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/sloop.glb',
    scale: 3.3, yOffset: 7.8, rotOffset: 0,
  },
  brigantine: {
    price: 7000, 
    currency: 'gold',
    hp: 1000, 
    maxCannons: 15, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/brigantine.glb',
    scale: 0.5, yOffset: 3.7, rotOffset: 0,
  },
  schooner: {
    price: 7000, 
    currency: 'gold',
    hp: 500, 
    maxCannons: 15, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/schooner.glb',
    scale: 1.5, yOffset: 5.6, rotOffset: 0,
  },
  galleon: {
    price: 10000, 
    currency: 'gold',
    hp: 2000, 
    maxCannons: 20, 
    sails: 1,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/galleon.glb',
    scale: 2.2, yOffset: 4.6, rotOffset: 90 * Math.PI / 180,
  },
  frigate: {
    price: 10000, 
    currency: 'gold',
    hp: 1000, 
    maxCannons: 25, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/frigate.glb',
    scale: 0.6, yOffset: 4.3, rotOffset: 0,
  },

  // ── Navios Elite (comprados com dobrões na Ilha do Comércio) ────────────────
  ghost_pirate_ship: {
    price: 20000, 
    currency: 'dobrao', isElite: true,
    hp: 5000, 
    maxCannons: 30, 
    sails: 3,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.5,
    model: '/models/ships/legendary_ghost_pirate_ship.glb',
    scale: 1, yOffset: 7, rotOffset: 0 * Math.PI / 180,
  },
  royal_fortune: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 20000, 
    maxCannons: 40, 
    sails: 3,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/royal_fortune.glb',
    scale: 3.2, yOffset: 3.5, rotOffset: 0 * Math.PI / 180,
  },
  adventure_galley: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 20000, 
    maxCannons: 45, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/adventure_galley.glb',
    scale: 3, yOffset: 3.5, rotOffset: 180 * Math.PI / 180,
  },
  whydah_galley: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 15000, 
    maxCannons: 40, 
    sails: 3,
    speedMult: 1.5, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/whydah_galley.glb',
    scale: 4.6, yOffset: 1.9, rotOffset: 90 * Math.PI / 180,
  },
  queen_annes_revenge: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 15000, 
    maxCannons: 45, 
    sails: 3,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/queen_annes_revenge.glb',
    scale: 2.1, yOffset: 3, rotOffset: 0,
  },
  fancy: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 20000, 
    maxCannons: 40, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/fancy.glb',
    scale: 14.8, yOffset: 3.5, rotOffset: 0,
  },
};

// ── SHIP_RELIQC — mana máxima e slots de relíquia por navio ───────────────────
const SHIP_RELIQC = {
  fragata:             { maxMana: 4,  maxHelic: 1 },
  sloop:               { maxMana: 5, maxHelic: 2 },
  brigantine:          { maxMana: 5, maxHelic: 2 },
  schooner:            { maxMana: 5, maxHelic: 2 },
  galleon:             { maxMana: 6, maxHelic: 3 },
  frigate:             { maxMana: 6, maxHelic: 3 },
  ghost_pirate_ship:   { maxMana: 8, maxHelic: 3 },
  royal_fortune:       { maxMana: 10, maxHelic: 4 },
  adventure_galley:    { maxMana: 10, maxHelic: 4 },
  whydah_galley:       { maxMana: 10, maxHelic: 4 },
  queen_annes_revenge: { maxMana: 10, maxHelic: 4 },
  fancy:               { maxMana: 10, maxHelic: 4 },
};

// ── SHIP_UPGRADE_DEFS — upgrades comprados na ilha (vida, defesa, dano) ───────
// dobroes: custo fixo por nível | goldDustPerLevel: pó de ouro escala × nível atual
const SHIP_UPGRADE_DEFS = [
  { id: 'hp',      icon: '❤️', label: 'Vida do Navio',  dobroes: 20000, goldDustPerLevel: 100, maxLevel: 5 },
  { id: 'defense', icon: '🛡', label: 'Defesa do Navio', dobroes: 20000, goldDustPerLevel: 100, maxLevel: 5 },
  { id: 'damage',  icon: '⚔️', label: 'Dano do Navio',   dobroes: 30000, goldDustPerLevel: 100, maxLevel: 5 },
];

module.exports = { SHIP_DEFS, SHIP_RELIQC, SHIP_UPGRADE_DEFS };
