// constants/ships.js — Navios, slots de relíquia e upgrades de ilha

// ── SHIP_DEFS ─────────────────────────────────────────────────────────────────
const SHIP_DEFS = {
  fragata: {
    price: 0, 
    currency: 'free',
    hp: 200, 
    maxCannons: 5, 
    sails: 1,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/fragata.glb',
    scale: 2.5, yOffset: -12.3, rotOffset: 270 * Math.PI / 180,
  },
  sloop: {
    price: 5000, 
    currency: 'gold',
    hp: 500, 
    maxCannons: 10, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/sloop.glb',
    scale: 3.3, yOffset: 7.8, rotOffset: 0,
  },
  brigantine: {
    price: 7000, 
    currency: 'gold',
    hp: 1000, 
    maxCannons: 15, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/brigantine.glb',
    scale: 0.5, yOffset: 3.7, rotOffset: 0,
  },
  schooner: {
    price: 7000, 
    currency: 'gold',
    hp: 500, 
    maxCannons: 15, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/schooner.glb',
    scale: 1.5, yOffset: 5.6, rotOffset: 0,
  },
  galleon: {
    price: 10000, 
    currency: 'gold',
    hp: 2000, 
    maxCannons: 20, 
    sails: 1,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/galleon.glb',
    scale: 2.2, yOffset: 4.6, rotOffset: 90 * Math.PI / 180,
  },
  frigate: {
    price: 10000, 
    currency: 'gold',
    hp: 1000, 
    maxCannons: 25, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0,
    model: '/models/ships/frigate.glb',
    scale: 0.6, yOffset: 4.3, rotOffset: 0,
  },

  // ── Navios Elite (comprados com dobrões na Ilha do Comércio) ────────────────
  ghost_pirate_ship: {
    price: 20000, 
    currency: 'dobrao', isElite: true,
    hp: 5000, 
    maxCannons: 30, 
    sails: 3,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.5,
    model: '/models/ships/legendary_ghost_pirate_ship.glb',
    scale: 1, yOffset: 7, rotOffset: 0 * Math.PI / 180,
  },
  royal_fortune: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 20000, 
    maxCannons: 40, 
    sails: 3,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/royal_fortune.glb',
    scale: 3.2, yOffset: 3.5, rotOffset: 0 * Math.PI / 180,
  },
  adventure_galley: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 20000, 
    maxCannons: 45, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/adventure_galley.glb',
    scale: 3, yOffset: 3.5, rotOffset: 180 * Math.PI / 180,
  },
  whydah_galley: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 15000, 
    maxCannons: 40, 
    sails: 3,
    speedMult: 1.5, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/whydah_galley.glb',
    scale: 4.6, yOffset: 1.9, rotOffset: 90 * Math.PI / 180,
  },
  queen_annes_revenge: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 15000, 
    maxCannons: 45, 
    sails: 3,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/queen_annes_revenge.glb',
    scale: 2.1, yOffset: 3, rotOffset: 0,
  },
  fancy: {
    price: 70000, 
    currency: 'dobrao', isElite: true,
    hp: 20000, 
    maxCannons: 40, 
    sails: 2,
    speedMult: 1.0, 
    damageMult: 1.0, 
    dropBonus: 0.1,
    model: '/models/ships/fancy.glb',
    scale: 14.8, yOffset: 3.5, rotOffset: 0,
  },
};

// ── SHIP_RELIQC — mana máxima e slots de relíquia por navio ───────────────────
const SHIP_RELIQC = {
  fragata:             { maxMana: 4,  maxHelic: 1 },
  sloop:               { maxMana: 5, maxHelic: 2 },
  brigantine:          { maxMana: 5, maxHelic: 2 },
  schooner:            { maxMana: 5, maxHelic: 2 },
  galleon:             { maxMana: 6, maxHelic: 3 },
  frigate:             { maxMana: 6, maxHelic: 3 },
  ghost_pirate_ship:   { maxMana: 8, maxHelic: 3 },
  royal_fortune:       { maxMana: 10, maxHelic: 4 },
  adventure_galley:    { maxMana: 10, maxHelic: 4 },
  whydah_galley:       { maxMana: 10, maxHelic: 4 },
  queen_annes_revenge: { maxMana: 10, maxHelic: 4 },
  fancy:               { maxMana: 10, maxHelic: 4 },
  // ── Barcos raros (Mapa Bônus) ─────────────────────────────────────────────
  colossal_ghost_pirate_galleon:   { maxMana: 10, maxHelic: 4 },
  massive_imperial_warship:        { maxMana: 10, maxHelic: 4 },
  gigantic_mechanical_pirate_ship: { maxMana: 10, maxHelic: 4 },
};

// ── SHIP_UPGRADE_DEFS — upgrades comprados na ilha (vida, defesa, dano) ───────
// dobroes: custo fixo por nível | goldDustPerLevel: pó de ouro escala × nível atual
const SHIP_UPGRADE_DEFS = [
  { id: 'hp',      icon: '❤️', label: 'Vida do Navio',  dobroes: 20000, goldDustPerLevel: 100, maxLevel: 5 },
  { id: 'defense', icon: '🛡', label: 'Defesa do Navio', dobroes: 20000, goldDustPerLevel: 100, maxLevel: 5 },
  { id: 'damage',  icon: '⚔️', label: 'Dano do Navio',   dobroes: 30000, goldDustPerLevel: 100, maxLevel: 5 },
];

// ── BONUS_NPC_DEFS — navios piratas NPC que usam canhões (usesCannons: true) ────
// Esses NPCs disparam projéteis reais via fireInterval, não usam ATTACK_DEFS.
// Podem ser referenciados em MAP_DEFS via campo `npc` ou como NPCs extras em mapas.
const BONUS_NPC_DEFS = {
  corsair_sloop: {
    names:           ['Corsário Sloop', 'Pirata Ligeiro'],
    baseHp:          200,
    baseDamage:      12,
    fireInterval:    3000,
    cannonCount:     2,
    cannonRange:     155, // c6=150, NPC não fica em desvantagem de alcance
    usesCannons:     true,
    hullColor:       0x3a1a0a,
    sailColor:       0xcc3333,
    flagColor:       0xcc2222,
    xpPerKill:       15,
    goldMin:         40,
    goldMax:         60,
    hpPerTier:       0.05,
    dmgPerTier:      0.08,
    goldPerTier:     0.03,
    model:           '/models/ships/sloop.glb',
    scale:           3.3,
    yOffset:         7.8,
    rotOffset:       0,
    hitRadius:       10,
    relicDropChance: 0.01,
    ammoTiers: [
      { minKills: 0,   ammo: 'bala_ferro' },
      { minKills: 100, ammo: 'bala_gelo'  },
    ],
  },

  buccaneer_brigantine: {
    names:           ['Bucaneiro Brigantim', 'Corsário Brigantim'],
    baseHp:          500,
    baseDamage:      25,
    fireInterval:    3500,
    cannonCount:     4,
    cannonRange:     165,
    usesCannons:     true,
    hullColor:       0x1a0a0a,
    sailColor:       0x220000,
    flagColor:       0x110000,
    xpPerKill:       30,
    goldMin:         80,
    goldMax:         120,
    hpPerTier:       0.07,
    dmgPerTier:      0.10,
    goldPerTier:     0.04,
    model:           '/models/ships/brigantine.glb',
    scale:           0.5,
    yOffset:         3.7,
    rotOffset:       0,
    hitRadius:       12,
    relicDropChance: 0.02,
    ammoTiers: [
      { minKills: 0,   ammo: 'bala_ferro' },
      { minKills: 150, ammo: 'bala_fogo'  },
    ],
  },

  navy_galleon: {
    names:           ['Galeão Naval', 'Galeão de Guerra'],
    baseHp:          1200,
    baseDamage:      50,
    fireInterval:    4000,
    cannonCount:     6,
    cannonRange:     175,
    usesCannons:     true,
    hullColor:       0x0a0a1a,
    sailColor:       0x223399,
    flagColor:       0x112288,
    xpPerKill:       60,
    goldMin:         150,
    goldMax:         250,
    hpPerTier:       0.10,
    dmgPerTier:      0.12,
    goldPerTier:     0.05,
    model:           '/models/ships/galleon.glb',
    scale:           2.2,
    yOffset:         4.6,
    rotOffset:       90 * Math.PI / 180,
    hitRadius:       14,
    relicDropChance: 0.04,
    ammoTiers: [
      { minKills: 0,   ammo: 'bala_ferro'     },
      { minKills: 200, ammo: 'bala_perfurante' },
    ],
  },

  elite_frigate: {
    names:           ['Fragata Elite', 'Fragata Imperial'],
    baseHp:          3000,
    baseDamage:      120,
    fireInterval:    4500,
    cannonCount:     8,
    cannonRange:     190,
    usesCannons:     true,
    hullColor:       0x0f0f0f,
    sailColor:       0x550000,
    flagColor:       0x330000,
    xpPerKill:       120,
    goldMin:         300,
    goldMax:         500,
    hpPerTier:       0.12,
    dmgPerTier:      0.15,
    goldPerTier:     0.06,
    model:           '/models/ships/frigate.glb',
    scale:           0.6,
    yOffset:         4.3,
    rotOffset:       0,
    hitRadius:       14,
    relicDropChance: 0.06,
    ammoTiers: [
      { minKills: 0,   ammo: 'bala_ferro'     },
      { minKills: 300, ammo: 'bala_sangue'    },
    ],
  },
};

module.exports = { SHIP_DEFS, SHIP_RELIQC, SHIP_UPGRADE_DEFS, BONUS_NPC_DEFS };
